Repository dogether-project/dogether-iOS, pull requests merged in 2025-04, with the labels that each got.

#6 스플래시, 온보딩 화면 수정
  dogether/Presentation/Base/BaseViewController.swift
  dogether/Presentation/Features/Onboarding/OnboardingViewController.swift
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/1024.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/114.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/120.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/180.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/29.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/40.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/57.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/58.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/60.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/80.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/87.png
  dogether/Resource/Asset/Assets.xcassets/AppIcon.appiconset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Logo/logo.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Logo/logo.imageset/logo.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Logo/logo.imageset/logo_V2.png
Labels: 🛠️ refactor

#16 NavigationHeader UI와 네이밍을 수정했어요
  dogether/Presentation/Common/NavigationHeader.swift
  dogether/Presentation/Features/GroupCreate/GroupCreateViewController.swift
  dogether/Presentation/Features/GroupJoin/GroupJoinViewController.swift
  dogether/Presentation/Features/MyPage/MyPageViewController.swift
  dogether/Presentation/Features/Ranking/RankingViewController.swift
  dogether/Presentation/Features/TodoWrite/TodoWriteViewController.swift
Labels: 🎨 design, 🛠️ refactor

#12 그룹가입화면을 리팩토링했어요.
  dogether/Data/RepositoryTest/GroupRepositoryTest.swift
  dogether/Domain/Entity/Enum/GroupJoinStatus.swift
  dogether/Presentation/Features/GroupJoin/GroupJoinViewController.swift
  dogether/Presentation/Features/GroupJoin/GroupJoinViewModel.swift
Labels: 🎨 design, 🐥 feat, 🛠️ refactor
