Repository dogether-project/dogether-iOS, pull requests merged in 2025-07, with the labels that each got.

#59 강제 업데이트 화면을 추가했어요
  dogether/Data/DataSources/AppInfoDataSource.swift
  dogether/Data/Network/NetworkEndpoint.swift
  dogether/Data/Network/Response/CheckUpdateResponse.swift
  dogether/Data/Network/Router/AppInfoRouter.swift
  dogether/Data/Repository/AppInfoRepository.swift
  dogether/Data/RepositoryTest/AppInfoRepositoryTest.swift
  dogether/Domain/Protocol/AppInfoProtocol.swift
  dogether/Domain/UseCase/AppLaunchUseCase.swift
  dogether/Presentation/Common/DogetherButton.swift
  dogether/Presentation/Features/Splash/SplashViewController.swift
  dogether/Presentation/Features/Splash/SplashViewModel.swift
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/partyDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/partyDosik.imageset/partyDosik.png
  dogether/Utility/Manager/DIManager.swift
Labels: 🐥 feat

#63 필터 선택 방식을 통일했어요
  dogether/Presentation/Features/CertificationList/Components/CertificationFilterView.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationListContentView.swift
  dogether/Presentation/Features/Main/Components/TodoListView.swift
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Presentation/Features/Main/MainViewModel.swift
Labels: 🎨 design, 🐥 feat

#68 인증 관련 아이콘 이미지 크기, 디자인 수정 반영
  dogether/Domain/Entity/Enum/FilterTypes.swift
  dogether/Domain/Entity/Enum/TodoStatus.swift
  dogether/Presentation/Common/FilterButton.swift
  dogether/Presentation/Common/TodoStatusButton.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationSummaryView.swift
  dogether/Presentation/Features/Main/Components/TodoListItemButton.swift
  dogether/Presentation/Features/Modality/Views/ExaminationModalityView.swift
  dogether/Presentation/Features/Ranking/Components/RankingView.swift
  dogether/Presentation/Features/Stats/Components/StatsSummaryView.swift
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/approve.imageset/approve.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/certification.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/certification.imageset/badge.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/certification.imageset/certification.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/certification2.imageset/certification2.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/certification_gray.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/certification_gray.imageset/certification_gray.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/reject.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/reject.imageset/denied.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/reject.imageset/reject.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/wait.imageset/wait.png
Labels: 🎨 design, 🛠️ refactor

#64 에러처리 화면을 추가해요.
  dogether/Data/Model/DogetherCodes.swift
  dogether/Data/Network/NetworkError.swift
  dogether/Data/Network/NetworkManager.swift
  dogether/Data/Network/NetworkService.swift
  dogether/Data/RepositoryTest/GroupRepositoryTest.swift
  dogether/Domain/UseCase/AuthUseCase.swift
  dogether/Presentation/Common/Error/ErrorHandlingManager.swift
  dogether/Presentation/Common/Error/ErrorTemplateConfig.swift
  dogether/Presentation/Common/Error/ErrorView.swift
  dogether/Presentation/Common/Error/ErrorViewController.swift
  dogether/Presentation/Features/Certification/CertificationSupplyViewController.swift
  dogether/Presentation/Features/CertificationList/CertificationListViewController.swift
  dogether/Presentation/Features/CertificationList/CertificationListViewModel.swift
  dogether/Presentation/Features/GroupCreate/GroupCreateViewController.swift
  dogether/Presentation/Features/GroupJoin/GroupJoinViewController.swift
  dogether/Presentation/Features/GroupManagement/GroupManagementViewController.swift
  dogether/Presentation/Features/GroupManagement/GroupManagementViewModel.swift
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Presentation/Features/MemberCertification/MemberCertificationViewController.swift
  dogether/Presentation/Features/MyPage/MyPageViewController.swift
  dogether/Presentation/Features/Ranking/RankingViewController.swift
  dogether/Presentation/Features/Setting/SettingViewController.swift
  dogether/Presentation/Features/Stats/Components/StatsContentView.swift
  dogether/Presentation/Features/Stats/StatsViewController.swift
  dogether/Presentation/Features/Stats/StatsViewModel.swift
  dogether/Presentation/Features/TodoWrite/TodoWriteViewController.swift
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/dosikArm.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/dosikArm.imageset/dusikArm.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/failDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/failDosik.imageset/failDusik.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/glassDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/glassDosik.imageset/glassDusik.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/happyDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/happyDosik.imageset/dusik2.svg
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/headacheDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/headacheDosik.imageset/headacheDusik.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/iceDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/iceDosik.imageset/iceDusik.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/sweatDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/sweatDosik.imageset/sweatDusik.png
  dogether/Utility/Coordinator/NavigationCoordinator.swift
Labels: 🎨 design, 🐥 feat, 🛠️ refactor

#71 Model을 분리했어요
  dogether/Data/DataSources/AuthDataSource.swift
  dogether/Data/DataSources/GroupsDataSource.swift
  dogether/Data/Network/Request/CreateGroupRequest.swift
  dogether/Data/Network/Response/GetMyGroupResponse.swift
  dogether/Data/Network/Router/GroupsRouter.swift
  dogether/Data/Repository/AuthRepository.swift
  dogether/Data/Repository/ChallengeGroupsRepository.swift
  dogether/Data/Repository/GroupRepository.swift
  dogether/Data/RepositoryTest/AuthRepositoryTest.swift
  dogether/Data/RepositoryTest/ChallengeGroupsRepositoryTest.swift
  dogether/Data/RepositoryTest/GroupRepositoryTest.swift
  dogether/Domain/Entity/Enum/LoginDomains.swift
  dogether/Domain/Entity/Model/ProfileInfo.swift
  dogether/Domain/Protocol/AuthProtocol.swift
  dogether/Domain/Protocol/ChallengeGroupsProtocol.swift
  dogether/Domain/Protocol/GroupProtocol.swift
  dogether/Domain/UseCase/AuthUseCase.swift
  dogether/Domain/UseCase/ChallengeGroupUseCase.swift
  dogether/Domain/UseCase/GroupUseCase.swift
  dogether/Domain/UseCase/MyProfileUseCase.swift
  dogether/Domain/UseCase/TodoCertificationsUseCase.swift
  dogether/Presentation/Features/Certification/CertificationSupplyViewController.swift
  dogether/Presentation/Features/Certification/CertificationViewController.swift
  dogether/Presentation/Features/Certification/CertificationViewModel.swift
  dogether/Presentation/Features/Dashboard/Components/MyDashboardCollectionViewCell.swift
  dogether/Presentation/Features/Dashboard/MyDashboardViewController.swift
  dogether/Presentation/Features/GroupCreate/GroupCreateViewModel.swift
  dogether/Presentation/Features/GroupJoin/GroupJoinViewModel.swift
  dogether/Presentation/Features/GroupManagement/Components/GroupManagementCell.swift
  dogether/Presentation/Features/GroupManagement/GroupManagementViewController.swift
  dogether/Presentation/Features/GroupManagement/GroupManagementViewModel.swift
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Presentation/Features/Modality/ModalityViewModel.swift
  dogether/Presentation/Features/MyPage/MyPageViewController.swift
  dogether/Presentation/Features/MyPage/MyPageViewModel.swift
  dogether/Presentation/Features/Onboarding/OnboardingViewModel.swift
  dogether/Presentation/Features/Setting/SettingViewModel.swift
  dogether/Presentation/Features/Stats/StatsViewModel.swift
  dogether/Utility/Coordinator/NavigationCoordinator.swift
Labels: 🛠️ refactor

#78 그룹원 인증 정보 'readTodo' 호출 로직을 수정했어요
  dogether/Domain/UseCase/ChallengeGroupUseCase.swift
  dogether/Presentation/Features/MemberCertification/MemberCertificationViewController.swift
  dogether/Presentation/Features/MemberCertification/MemberCertificationViewModel.swift
Labels: 🐞 fix, 🛠️ refactor

#80 바텀시트의 핸들뷰를 제거했어요.
  dogether/Presentation/Common/BottmSheet/BottomSheetViewController.swift
Labels: 🛠️ refactor
