Repository dogether-project/dogether-iOS, pull requests merged in 2025-05, with the labels that each got.

#19 랭킹 화면을 수정하고 그룹원 인증 정보 화면을 추가했어요
  dogether/Data/DataSources/ChallengeGroupsDataSource.swift
  dogether/Data/DataSources/GroupsDataSource.swift
  dogether/Data/DataSources/TodosDataSource.swift
  dogether/Data/Model/RankingModel.swift
  dogether/Data/Network/NetworkEndpoint.swift
  dogether/Data/Network/Response/GetMemberTodosResponse.swift
  dogether/Data/Network/Response/GetRankingResponse.swift
  dogether/Data/Network/Response/GetTeamSummaryResponse.swift
  dogether/Data/Network/Router/ChallengeGroupsRouter.swift
  dogether/Data/Network/Router/GroupsRouter.swift
  dogether/Data/Repository/ChallengeGroupsRepository.swift
  dogether/Data/Repository/GroupRepository.swift
  dogether/Data/Repository/PopupRepository.swift
  dogether/Data/Repository/TodoRepository.swift
  dogether/Data/RepositoryTest/ChallengeGroupsRepositoryTest.swift
  dogether/Data/RepositoryTest/GroupRepositoryTest.swift
  dogether/Data/RepositoryTest/TodoCertificationsRepositoryTest.swift
  dogether/Data/RepositoryTest/TodoRepositoryTest.swift
  dogether/Domain/Entity/Enum/Directions.swift
  dogether/Domain/Entity/Enum/TodoStatus.swift
  dogether/Domain/Entity/Model/MemberCertificationInfo.swift
  dogether/Domain/Protocol/ChallengeGroupsProtocol.swift
  dogether/Domain/Protocol/GroupProtocol.swift
  dogether/Domain/UseCase/ChallengeGroupUseCase.swift
  dogether/Domain/UseCase/GroupUseCase.swift
  dogether/Domain/UseCase/TodoUseCase.swift
  dogether/Presentation/Common/CertificationImageView.swift
  dogether/Presentation/Common/NavigationHeader.swift
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Presentation/Features/Main/MainViewModel.swift
  dogether/Presentation/Features/MemberCertification/Components/ThumbnailView.swift
  dogether/Presentation/Features/MemberCertification/MemberCertificationViewController.swift
  dogether/Presentation/Features/MemberCertification/MemberCertificationViewModel.swift
  dogether/Presentation/Features/Modality/Views/ExaminationModalityView.swift
  dogether/Presentation/Features/Popup/Views/CertificationInfoPopupView.swift
  dogether/Presentation/Features/Popup/Views/CertificationPopupView.swift
  dogether/Presentation/Features/Ranking/Components/RankingImageView.swift
  dogether/Presentation/Features/Ranking/Components/RankingTableViewCell.swift
  dogether/Presentation/Features/Ranking/Components/RankingTopView.swift
  dogether/Presentation/Features/Ranking/Components/RankingView.swift
  dogether/Presentation/Features/Ranking/RankingViewController.swift
  dogether/Presentation/Features/Ranking/RankingViewModel.swift
  dogether/Presentation/Features/TodoWrite/TodoWriteViewModel.swift
  dogether/Resource/Asset/Assets.xcassets/Icon/Logo/logo.imageset/logo.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/embarrassedDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/embarrassedDosik.imageset/embarrassedDosik.png
  dogether/Utility/Extension/ArrayExt.swift
  dogether/Utility/Manager/DIManager.swift
Labels: 🎨 design, 🐥 feat, 🛠️ refactor

#23 투두 작성화면을 수정했어요.
  dogether/Domain/Entity/Enum/PopupTypes.swift
  dogether/Presentation/Features/Popup/Views/AlertPopupView.swift
  dogether/Presentation/Features/TodoWrite/TodoWriteViewController.swift
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/caution.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/caution.imageset/caution.png
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/emptyDusik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Status/emptyDusik.imageset/emptyDusik.png
Labels: 🎨 design, 🐥 feat, 🛠️ refactor

#25 바뀐 그룹 생성 화면을 적용했어요
  dogether/Data/Network/Response/JoinGroupResponse.swift
  dogether/Data/RepositoryTest/GroupRepositoryTest.swift
  dogether/Domain/UseCase/GroupUseCase.swift
  dogether/Presentation/Common/DogetherGroupInfo.swift
  dogether/Presentation/Features/GroupComplete/CompleteViewController.swift
  dogether/Presentation/Features/GroupCreate/GroupCreateViewController.swift
  dogether/Presentation/Features/GroupCreate/GroupCreateViewModel.swift
Labels: 🎨 design, 🛠️ refactor

#26 일부 팝업을 뷰로 전환했어요
  dogether/Data/RepositoryTest/TodoCertificationsRepositoryTest.swift
  dogether/Domain/Entity/Enum/PopupTypes.swift
  dogether/Presentation/Common/CertificationImageView.swift
  dogether/Presentation/Common/DogetherTextView.swift
  dogether/Presentation/Features/Certification/CertificationInfoViewController.swift
  dogether/Presentation/Features/Certification/CertificationSupplyViewController.swift
  dogether/Presentation/Features/Certification/CertificationViewController.swift
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Presentation/Features/MemberCertification/MemberCertificationViewController.swift
  dogether/Presentation/Features/Modality/ModalityViewController.swift
  dogether/Presentation/Features/Modality/Views/ExaminationModalityView.swift
  dogether/Presentation/Features/Popup/PopupViewController.swift
  dogether/Presentation/Features/Popup/PopupViewModel.swift
  dogether/Presentation/Features/Popup/Views/CertificationInfoPopupView.swift
  dogether/Presentation/Features/Popup/Views/CertificationPopupView.swift
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/cameraDosik.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Dosik/cameraDosik.imageset/cameraDosik.png
  dogether/Utility/Extension/UIImageExt.swift
  dogether/Utility/Extension/UIImageViewExt.swift
Labels: 🎨 design, 🐥 feat

#28 바뀐 투두 추가 API를 반영했어요
  dogether/Data/DataSources/ChallengeGroupsDataSource.swift
  dogether/Data/Network/Router/ChallengeGroupsRouter.swift
  dogether/Data/Repository/ChallengeGroupsRepository.swift
  dogether/Data/RepositoryTest/ChallengeGroupsRepositoryTest.swift
  dogether/Domain/Protocol/ChallengeGroupsProtocol.swift
  dogether/Domain/UseCase/ChallengeGroupUseCase.swift
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Presentation/Features/TodoWrite/TodoWriteViewController.swift
  dogether/Presentation/Features/TodoWrite/TodoWriteViewModel.swift
Labels: 🛠️ refactor

#31 메인화면 isHidden 로직을 개선했어요
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Utility/Manager/DIManager.swift
Labels: 🐞 fix

#33 바텀시트에 새 그룹추가하기 버튼을 추가해요.
  dogether/Presentation/Common/BottmSheet/BottomSheetViewController.swift
  dogether/Presentation/Features/GroupCreate/GroupCreateViewController.swift
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Presentation/Features/MyPage/MyPageViewController.swift
  dogether/Resource/Asset/Assets.xcassets/Icon/Button/plus2.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/Button/plus2.imageset/plus_3.svg
  dogether/Resource/Asset/Assets.xcassets/Icon/profile/profile5.imageset/Contents.json
  dogether/Resource/Asset/Assets.xcassets/Icon/profile/profile5.imageset/profile5.png
Labels: 🐥 feat, 🛠️ refactor

#38 마이페이지 프로필 이미지, 이름 API를 연결했어요.
  dogether/Data/DataSources/MyProfileDataSource.swift
  dogether/Data/Network/NetworkEndpoint.swift
  dogether/Data/Network/Response/MyProfileResponse.swift
  dogether/Data/Network/Router/MyProfileRouter.swift
  dogether/Data/Repository/MyProfileRepository.swift
  dogether/Data/RepositoryTest/MyProfileRepositoryTest.swift
  dogether/Domain/Protocol/MyProfileProtocol.swift
  dogether/Domain/UseCase/MyProfileUseCase.swift
  dogether/Presentation/Features/MyPage/MyPageViewController.swift
  dogether/Presentation/Features/MyPage/MyPageViewModel.swift
  dogether/Utility/Manager/DIManager.swift
Labels: 🐥 feat, 🛠️ refactor

#40 통계 페이지, 바텀시트 이슈를 수정했어요.
  dogether/Presentation/Common/BottmSheet/BottomSheetViewController.swift
  dogether/Presentation/Features/CertificationList/CertificationListViewController.swift
  dogether/Presentation/Features/CertificationList/CertificationListViewModel.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationListContentView.swift
  dogether/Presentation/Features/CertificationList_Park/CertificationListViewController_Park.swift
  dogether/Presentation/Features/CertificationList_Park/Components/CertificationCollectionViewCell_Park.swift
  dogether/Presentation/Features/CertificationList_Park/Components/CertificationListCollectionViewCell_Park.swift
  dogether/Presentation/Features/Main/MainViewController.swift
  dogether/Presentation/Features/Main/MainViewModel.swift
  dogether/Presentation/Features/Stats/StatsViewController.swift
  dogether/Presentation/Features/Stats/StatsViewModel.swift
Labels: 🛠️ refactor

#42 LoadingView를 추가했어요
  dogether/Data/Network/NetworkManager.swift
  dogether/Presentation/Common/LoadingViewController.swift
  dogether/Utility/Manager/LoadingManager.swift
Labels: 🐥 feat

#43 인증 목록 페이지 이슈를 해결했어요.
  dogether.xcodeproj/project.pbxproj
  dogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dogether/Data/DataSources/CertificationListDataSource.swift
  dogether/Data/Network/Response/CertificationListResponse.swift
  dogether/Data/Network/Router/CertificationListRouter.swift
  dogether/Domain/Entity/Model/TodoInfo.swift
  dogether/Presentation/Common/FilterButton.swift
  dogether/Presentation/Features/CertificationList/CertificationListViewController.swift
  dogether/Presentation/Features/CertificationList/CertificationListViewModel.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationFilterView.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationListCell.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationListContentView.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationSortButton.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationSortOption.swift
Labels: 🛠️ refactor

#45 통계페이지 바텀시트띄우는 액션을 수정했어요.
  dogether/Presentation/Features/Certification/CertificationInfoViewController.swift
  dogether/Presentation/Features/CertificationList/Components/CertificationListCell.swift
  dogether/Presentation/Features/Stats/Components/StatsContentView.swift
  dogether/Presentation/Features/Stats/Components/StatsGroupInfoView.swift
Labels: 🛠️ refactor
